spring:
  application:
    name: Bank Application

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_url}
    username: ${DB_username}
    password: ${DB_password}
    driver-class-name: org.postgresql.Driver

  # Flyway Migration Configuration
  flyway:
    enabled: true

  # JPA/Hibernate Configuration
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Disable Spring's default SQL script initialization so Flyway handles everything
  sql:
    init:
      mode: never